Feature/angular default flow example
cleverpine/virava-fe pull request #8
Opened 2023-05-18 07:36 UTC by AKalvachev

2023-05-18 09:49 UTC, NikolaEnchevCP approved these changes

2023-05-22 10:16 UTC, yordanatanasov-cp requested changes
.vscode folder should be ignored

2023-05-22 10:16 UTC, yordanatanasov-cp commented on examples/angular-default/src/app/interceptors/api.interceptor.ts
> +        if (err.status === 401) {
Add todo to move this error check inside Virava (or export it to a callback and check it via virava, we have some logic for that there)

2023-05-22 11:26 UTC, yordanatanasov-cp approved these changes

2023-05-22 11:49 UTC, merged